export const body = document.querySelector('body');
export const loader = document.querySelector('#loader');
export const navbar = document.querySelector('navbar');
export const formInputs = document.querySelectorAll('input, textarea');
export const submitButton = document.querySelector('button[type="submit"]');
export const modal = document.querySelector('.modal') ? document.querySelector('.modal')[0] : null;
export const cookieBanner = document.querySelector('#cookie-banner');
export const cookieBannerButton = document.querySelector('#cookie-banner-button');
export const selectors = document.querySelector('select');
export const options = document.getElementsByTagName('option');
